conversations/urls.py
from django.urls import path
from .views import *

app_name = 'conversations'

urlpatterns = [
    path('inbox/<int:profile_friend>', inbox, name="inbox_new_chat"),
    path('inbox/', inbox, name="inbox"),
    path('chatbox/<int:chat_id>', chatbox, name="chatbox"),
    path('delete/message/<int:message_id>', delete_message ,name="delete_message"),
    path('delete/chat/<int:chat_id>', delete_chat ,name="delete_chat"),


]

djpenpal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('message/', include('conversations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', index, name="index"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register/", register, name="register"),
    path("profile/<int:profile_id>", profile, name="profile"),
    path("request/send/<int:to_profile_id>", send_request, name="send_request"),
    path("request/accept/<int:from_profile_id>", accept_friend_request, name="accept_request"),
    path("request/delete/<int:from_profile_id>", delete_friend_request, name="delete_request"),
    path("request/cancel/<int:to_profile_id>", cancel_request, name="cancel_request"),
    path("edit/",edit_profile,name="edit"),
    path("search/",search,name="search"),
    path("unfriend/<int:profile_id>",unfriend,name="unfriend"),
    
    
]

templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Penplas</title>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
</head>

<body class = "d-flex flex-column min-vh-100">
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">Penpals</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{{ request.user.profile.get_absolute_url }}">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'conversations:inbox' %}">Inbox</a>
              </li>
            {% endif%}          
        </ul>
      </div>
    </div>      
  </nav>


<div class="container mt-4">

   {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-{{ message.tags }}" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  

 
  

    {% block content %}


    {% endblock content %}
   

</div>


  {% if page_obj.has_other_pages %}

    <ul class="pagination justify-content-center">

      {% for ag in page_obj.paginator.page_range %}

        {% if page_obj.number == ag %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?{{s}}page={{ ag }}">{{ ag }} <span class="sr-only">(current)</span></a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{{s}}page={{ ag }}">{{ ag }}</a>
          </li>
        {% endif %}

      {% endfor %}

    </ul>

  {% endif %}






 
  <footer class="bg-dark text-white mt-auto">
    <div class="container-fluid py-4">
      <p class=" text-center ">Copyright &copy; Penpals 2020</p>
    </div>
  </footer>


  <script src="{% static  'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

 

  {% block js %}
  {% endblock js %}


</body>

</html>